-- DropPilot Supabase setup
-- This file documents the database structure, views, functions, RLS policies,
-- and RPC helpers needed to rebuild the Supabase backend.

-- =========================================================
-- TABLES
-- =========================================================

CREATE TABLE IF NOT EXISTS public.products (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name text NOT NULL,
  category text NOT NULL,
  price_eur numeric NOT NULL DEFAULT 0,
  cost_eur numeric NOT NULL DEFAULT 0,
  target_country text NOT NULL,
  ai_score numeric NOT NULL DEFAULT 0,
  active boolean NOT NULL DEFAULT true,
  supplier_url text DEFAULT '',
  notes text DEFAULT '',
  product_status text NOT NULL DEFAULT 'Pendiente',
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.sales (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  product_id bigint NOT NULL REFERENCES public.products(id) ON DELETE CASCADE,
  sale_amount_eur numeric NOT NULL DEFAULT 0,
  sale_amount_brl numeric NOT NULL DEFAULT 0,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.product_metrics (
  product_id bigint PRIMARY KEY REFERENCES public.products(id) ON DELETE CASCADE,
  times_sold integer NOT NULL DEFAULT 0,
  total_revenue numeric NOT NULL DEFAULT 0,
  updated_at timestamptz NOT NULL DEFAULT now()
);

-- =========================================================
-- PRODUCT METRICS REFRESH FUNCTION
-- =========================================================

CREATE OR REPLACE FUNCTION public.refresh_product_metrics(p_product_id bigint)
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
  DELETE FROM public.product_metrics
  WHERE product_id = p_product_id;

  INSERT INTO public.product_metrics (
    product_id,
    times_sold,
    total_revenue,
    updated_at
  )
  SELECT
    p_product_id,
    COUNT(*)::integer,
    COALESCE(SUM(sale_amount_eur), 0)::numeric,
    now()
  FROM public.sales
  WHERE product_id = p_product_id
  HAVING COUNT(*) > 0;
END;
$$;

-- =========================================================
-- SALES TRIGGER
-- =========================================================

CREATE OR REPLACE FUNCTION public.handle_sales_change()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
  IF TG_OP = 'INSERT' THEN
    PERFORM public.refresh_product_metrics(NEW.product_id);
    RETURN NEW;
  END IF;

  IF TG_OP = 'UPDATE' THEN
    PERFORM public.refresh_product_metrics(OLD.product_id);

    IF NEW.product_id <> OLD.product_id THEN
      PERFORM public.refresh_product_metrics(NEW.product_id);
    END IF;

    RETURN NEW;
  END IF;

  IF TG_OP = 'DELETE' THEN
    PERFORM public.refresh_product_metrics(OLD.product_id);
    RETURN OLD;
  END IF;

  RETURN NULL;
END;
$$;

DROP TRIGGER IF EXISTS sales_metrics_trigger ON public.sales;

CREATE TRIGGER sales_metrics_trigger
AFTER INSERT OR UPDATE OR DELETE ON public.sales
FOR EACH ROW
EXECUTE FUNCTION public.handle_sales_change();

-- =========================================================
-- PRODUCT RADAR VIEW
-- =========================================================

CREATE OR REPLACE VIEW public.product_radar AS
WITH base AS (
  SELECT
    p.id,
    p.name,
    p.category,
    p.price_eur,
    p.target_country,
    p.ai_score,
    COALESCE(p.cost_eur, 0)::numeric AS cost_eur,
    COALESCE(p.supplier_url, '') AS supplier_url,
    COALESCE(p.notes, '') AS notes,
    COALESCE(p.product_status, 'Pendiente') AS product_status,
    COALESCE(pm.times_sold, 0) AS times_sold,
    COALESCE(pm.total_revenue, 0)::numeric AS total_revenue
  FROM public.products p
  LEFT JOIN public.product_metrics pm
    ON pm.product_id = p.id
),

scored AS (
  SELECT
    id,
    name,
    category,
    price_eur,
    target_country,
    times_sold,
    total_revenue,
    cost_eur,
    supplier_url,
    notes,
    product_status,

    CASE
      WHEN cost_eur > 0
        THEN (price_eur - cost_eur)::numeric
      ELSE 0
    END AS unit_profit,

    CASE
      WHEN cost_eur > 0 AND price_eur > 0
        THEN (((price_eur - cost_eur) / price_eur) * 100)::numeric
      ELSE 0
    END AS margin_percent,

    CASE
      WHEN cost_eur > 0
        THEN (total_revenue - (times_sold * cost_eur))::numeric
      ELSE 0
    END AS total_profit,

    (
      CASE
        WHEN times_sold = 0 THEN ai_score * 0.45
        ELSE
          sqrt(times_sold) * 65
          + sqrt(total_revenue) * 4
          + ai_score * 0.15
      END

      +

      CASE
        WHEN cost_eur > 0 AND price_eur > 0
          THEN LEAST(((price_eur - cost_eur) / price_eur) * 100, 80) * 1.2
        ELSE 0
      END

      +

      CASE
        WHEN cost_eur > 0
          THEN sqrt(GREATEST(total_revenue - (times_sold * cost_eur), 0)) * 5
        ELSE 0
      END

      -

      CASE
        WHEN cost_eur > 0
          AND price_eur > 0
          AND ((price_eur - cost_eur) / price_eur) * 100 < 15
          THEN 80
        WHEN cost_eur > 0
          AND price_eur > 0
          AND ((price_eur - cost_eur) / price_eur) * 100 < 25
          THEN 35
        ELSE 0
      END
    )::numeric AS raw_score

  FROM base
),

ranked AS (
  SELECT
    id,
    name,
    category,
    price_eur,
    target_country,
    times_sold,
    total_revenue,
    raw_score,
    percent_rank() OVER (ORDER BY raw_score) AS percentile,
    cost_eur,
    unit_profit,
    margin_percent,
    total_profit,
    supplier_url,
    notes,
    product_status
  FROM scored
)

SELECT
  id,
  name,
  category,
  price_eur,
  target_country,
  times_sold,
  total_revenue,
  raw_score,
  percentile,
  CASE
    WHEN percentile >= 0.9 THEN '🔥 WINNER'
    WHEN percentile >= 0.75 THEN '🟢 STRONG'
    WHEN percentile >= 0.4 THEN '🟡 AVERAGE'
    ELSE '🔴 WEAK'
  END AS decision_label,
  cost_eur,
  unit_profit,
  margin_percent,
  total_profit,
  supplier_url,
  notes,
  product_status
FROM ranked;

-- =========================================================
-- RPC: RESET MARKET
-- =========================================================

CREATE OR REPLACE FUNCTION public.reset_market()
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
  DELETE FROM public.sales;
  DELETE FROM public.product_metrics;
END;
$$;

-- =========================================================
-- RPC: DELETE SINGLE SALE
-- =========================================================

CREATE OR REPLACE FUNCTION public.delete_sale(p_sale_id bigint)
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_product_id bigint;
BEGIN
  SELECT product_id
  INTO v_product_id
  FROM public.sales
  WHERE id = p_sale_id;

  IF v_product_id IS NULL THEN
    RETURN;
  END IF;

  DELETE FROM public.sales
  WHERE id = p_sale_id;

  PERFORM public.refresh_product_metrics(v_product_id);
END;
$$;

-- =========================================================
-- ROW LEVEL SECURITY
-- =========================================================

ALTER TABLE public.products ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.sales ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.product_metrics ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Authenticated can read products" ON public.products;
DROP POLICY IF EXISTS "Authenticated can insert products" ON public.products;
DROP POLICY IF EXISTS "Authenticated can update products" ON public.products;
DROP POLICY IF EXISTS "Authenticated can delete products" ON public.products;

CREATE POLICY "Authenticated can read products"
ON public.products
FOR SELECT
TO authenticated
USING (true);

CREATE POLICY "Authenticated can insert products"
ON public.products
FOR INSERT
TO authenticated
WITH CHECK (true);

CREATE POLICY "Authenticated can update products"
ON public.products
FOR UPDATE
TO authenticated
USING (true)
WITH CHECK (true);

CREATE POLICY "Authenticated can delete products"
ON public.products
FOR DELETE
TO authenticated
USING (true);

DROP POLICY IF EXISTS "Authenticated can read sales" ON public.sales;
DROP POLICY IF EXISTS "Authenticated can insert sales" ON public.sales;

CREATE POLICY "Authenticated can read sales"
ON public.sales
FOR SELECT
TO authenticated
USING (true);

CREATE POLICY "Authenticated can insert sales"
ON public.sales
FOR INSERT
TO authenticated
WITH CHECK (true);

DROP POLICY IF EXISTS "Authenticated can read product metrics" ON public.product_metrics;

CREATE POLICY "Authenticated can read product metrics"
ON public.product_metrics
FOR SELECT
TO authenticated
USING (true);

-- =========================================================
-- PERMISSIONS
-- =========================================================

REVOKE ALL ON public.products FROM anon;
REVOKE ALL ON public.sales FROM anon;
REVOKE ALL ON public.product_metrics FROM anon;

GRANT SELECT, INSERT, UPDATE, DELETE ON public.products TO authenticated;
GRANT SELECT, INSERT ON public.sales TO authenticated;
GRANT SELECT ON public.product_metrics TO authenticated;
GRANT SELECT ON public.product_radar TO authenticated;

REVOKE ALL ON FUNCTION public.reset_market() FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.reset_market() TO authenticated;

REVOKE ALL ON FUNCTION public.delete_sale(bigint) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.delete_sale(bigint) TO authenticated;

REVOKE ALL ON FUNCTION public.refresh_product_metrics(bigint) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.refresh_product_metrics(bigint) TO authenticated;